import image1 from './images/160504231940-lebron-james-cleveland-cavaliers-v-atlanta-hawks---game-two.1000x563.jpeg'
import image2 from './images/160510212144-serge-ibaka-lamarcus-aldridge-nba-playoffs-oklahoma-city-thunder-at-san-antonio-spurs.1000x563.jpeg'
import image3 from './images/160510212222-manu-ginobili-enes-kanter-nba-playoffs-oklahoma-city-thunder-at-san-antonio-spurs.1000x563.jpeg'
import image4 from './images/Game of throne wallpaper (2).jpg'
import image5 from './images/Game of throne wallpaper (35).jpg'
import image6 from './images/Game of throne wallpaper (38).jpg'
import image7 from './images/Game of throne wallpaper (9).jpg'


export const photoData = [
  {
    id: 1,
    title: "title 1",
    description: "description 1",
    category: "category1",
    keywords: "keyword1",
    privacy: "privacy1",
    image: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
    place_where_shot: " place where shot1",
    file_location: "file location1",
    uploaded_on: "uploaded on",
  },
  {
    id: 2,
    title: "title 2",
    description: "description 2",
    category: "category2",
    keywords: "keyword2",
    privacy: "privacy2",
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
    place_where_shot: " place where shot2",
    file_location: "file location2",
    uploaded_on: "uploaded on",
  },
  {
    id: 3,
    title: "title 3",
    description: "description 3",
    category: "category3",
    keywords: "keyword3",
    privacy: "privacy3",
    image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
    place_where_shot: " place where shot3",
    file_location: "file location3",
    uploaded_on: "uploaded on",
  },
  {
    id: 4,
    title: "title 4",
    description: "description 4",
    category: "category4",
    keywords: "keyword4",
    privacy: "privacy4",
    image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383",
    place_where_shot: " place where shot4",
    file_location: "file location4",
    uploaded_on: "uploaded on",
  },
  {
    id: 5,
    title: "title 5",
    description: "description 5",
    category: "category5",
    keywords: "keyword5",
    privacy: "privacy5",
    image: "https://images.unsplash.com/photo-1471357674240-e1a485acb3e1",
    place_where_shot: " place where shot5",
    file_location: "file location5",
    uploaded_on: "uploaded on",
  },
  {
    id: 6,
    title: "title 6",
    description: "description 6",
    category: "category6",
    keywords: "keyword6",
    privacy: "privacy6",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
    place_where_shot: " place where shot6",
    file_location: "file location6",
    uploaded_on: "uploaded on",
  },
  {
    id: 7,
    title: "title 7",
    description: "description 7",
    category: "category7",
    keywords: "keyword7",
    privacy: "privacy7",
    image: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
    place_where_shot: " place where shot7",
    file_location: "file location7",
    uploaded_on: "uploaded on",
  },
  {
    id: 8,
    title: "title 8",
    description: "description 8",
    category: "category8",
    keywords: "keyword8",
    privacy: "privacy8",
    image: image1,
    place_where_shot: " place where shot8",
    file_location: "file location8",
    uploaded_on: "uploaded on",
  },
  {
    id: 9,
    title: "title 9",
    description: "description 9",
    category: "category9",
    keywords: "keyword9",
    privacy: "privacy9",
    image: image2,
    place_where_shot: " place where shot9",
    file_location: "file location9",
    uploaded_on: "uploaded on",
  },
  {
    id: 10,
    title: "title 10",
    description: "description 10",
    category: "category10",
    keywords: "keyword10",
    privacy: "privacy10",
    image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
    place_where_shot: " place where shot10",
    file_location: "file location10",
    uploaded_on: "uploaded on",
  },
  {
    id: 11,
    title: "title 11",
    description: "description 11",
    category: "category11",
    keywords: "keyword11",
    privacy: "privacy11",
    image: image3,
    place_where_shot: " place where shot11",
    file_location: "file location11",
    uploaded_on: "uploaded on",
  },
  {
    id: 12,
    title: "title 12",
    description: "description 12",
    category: "category12",
    keywords: "keyword12",
    privacy: "privacy12",
    image: "https://images.unsplash.com/photo-1471357674240-e1a485acb3e1",
    place_where_shot: " place where shot12",
    file_location: "file location12",
    uploaded_on: "uploaded on",
  },
  {
    id: 13,
    title: "title 13",
    description: "description 13",
    category: "category13",
    keywords: "keyword13",
    privacy: "privacy13",
    image: image1,
    place_where_shot: " place where shot13",
    file_location: "file location13",
    uploaded_on: "uploaded on",
  },
  {
    id: 14,
    title: "title 14",
    description: "description 14",
    category: "category14",
    keywords: "keyword14",
    privacy: "privacy14",
    image: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
    place_where_shot: " place where shot14",
    file_location: "file location14",
    uploaded_on: "uploaded on",
  },
];